"""add confidence_score and provenance fields

Revision ID: 8e3368dc84ad
Revises: d92b44ac479f
Create Date: 2026-07-29 04:48:17.510582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3368dc84ad'
down_revision = 'd92b44ac479f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturers', sa.Column('confidence_score', sa.Float(), nullable=True, comment="0-1 trust level in this manufacturer's data_source_type classification/data quality. API-sourced data should generally score higher than scraped data; feeds into AI scoring in Phase 2."))
    op.add_column('variants', sa.Column('raw_source_url', sa.String(length=500), nullable=True, comment="Exact page/API URL this variant's data was pulled from. Lets us trace any price/spec back to its source and detect when a manufacturer has updated it."))
    op.add_column('variants', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True, comment="Last time this variant's data was confirmed fresh against raw_source_url."))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variants', 'last_verified_at')
    op.drop_column('variants', 'raw_source_url')
    op.drop_column('manufacturers', 'confidence_score')
    # ### end Alembic commands ###
