"""initial schema

Revision ID: d92b44ac479f
Revises: 
Create Date: 2026-07-28 10:06:22.953605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92b44ac479f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('data_source_type', sa.Enum('API', 'SCRAPER', 'MANUAL', 'UNKNOWN', name='datasourcetype'), nullable=False),
    sa.Column('has_open_api', sa.Boolean(), nullable=False),
    sa.Column('api_endpoint', sa.String(length=255), nullable=True),
    sa.Column('scraper_module', sa.String(length=150), nullable=True, comment='Dotted path to the manufacturer-specific scraper, e.g. app.pipeline.scrapers.tata'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=True)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.Column('launch_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_model'), 'cars', ['model'], unique=False)
    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PARTIAL', 'RUNNING', name='scrapestatus'), nullable=False),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_saved', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('transmission', sa.String(length=30), nullable=True),
    sa.Column('fuel', sa.String(length=30), nullable=True),
    sa.Column('engine', sa.String(length=50), nullable=True),
    sa.Column('power', sa.String(length=30), nullable=True),
    sa.Column('torque', sa.String(length=30), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('ride_quality', sa.Float(), nullable=True),
    sa.Column('city_friendliness', sa.Float(), nullable=True),
    sa.Column('highway_comfort', sa.Float(), nullable=True),
    sa.Column('maintenance_level', sa.Float(), nullable=True),
    sa.Column('resale_value', sa.Float(), nullable=True),
    sa.Column('service_network', sa.Float(), nullable=True),
    sa.Column('beginner_friendly', sa.Boolean(), nullable=True),
    sa.Column('family_score', sa.Float(), nullable=True),
    sa.Column('elderly_friendly', sa.Boolean(), nullable=True),
    sa.Column('premium_feel', sa.Float(), nullable=True),
    sa.Column('offroad_capability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id')
    )
    op.create_table('specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('seating', sa.Integer(), nullable=True),
    sa.Column('airbags', sa.Integer(), nullable=True),
    sa.Column('safety_rating', sa.Float(), nullable=True),
    sa.Column('ground_clearance', sa.Float(), nullable=True),
    sa.Column('boot_space', sa.Float(), nullable=True),
    sa.Column('wheelbase', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specifications')
    op.drop_table('ai_attributes')
    op.drop_table('variants')
    op.drop_table('scrape_logs')
    op.drop_index(op.f('ix_cars_model'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
